### ISSUE TITLE
Update http version

### ISSUE THREAD

**Issue by dmvvilela** [slimpotatoboy/discord_logger#4]
Please, I can't use it with https://pub.dev/packages/google_generative_ai because of http versioning.

**Comment by slimpotatoboy** [comment]
Resolved

**Comment by dmvvilela** [comment]
Hey @slimpotatoboy .. Problem is now you have analysis issue:

<img width="813" alt="Captura de Tela 2024-02-17 às 15 48 49" src="https://github.com/slimpotatoboy/discord_logger/assets/8460696/2976e694-c210-4233-b7fb-ac5c2b79cbf9">

Need newer dart sdk...

**Comment by slimpotatoboy** [comment]
ok I'll check it
